version: '2'
services:
    drvadim-app:
        image: drvadim
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:postgresql://drvadim-postgresql:5432/drVadim
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    drvadim-postgresql:
        extends:
            file: postgresql.yml
            service: drvadim-postgresql
