version: '2'
services:
    drvadim-postgresql:
        image: postgres:9.6.5
        # volumes:
        #     - ~/volumes/jhipster/drVadim/postgresql/:/var/lib/postgresql/data/
        environment:
            - POSTGRES_USER=drVadim
            - POSTGRES_PASSWORD=
        ports:
            - 5432:5432
